version: '3'

services:
  emailapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  services.portal:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  phone.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat

