version: '3'

services:
  emailapi:
    image: emailapi
    build:
      context: .
      dockerfile: EmailAPI\Dockerfile

  services.portal:
    image: services.portal
    build:
      context: .
      dockerfile: Services.Portal\Dockerfile


  phone.api:
    image: phone.api
    build:
      context: .
      dockerfile: Phone.API\Dockerfile

