// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Phone.API.Data;
using System;

namespace Phone.API.Migrations
{
    [DbContext(typeof(PhoneContext))]
    [Migration("20180201210733_AddFromNumber")]
    partial class AddFromNumber
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Phone.API.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("Phone.API.Models.PhoneContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("PhoneLogId");

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PhoneLogId");

                    b.ToTable("PhoneContact");
                });

            modelBuilder.Entity("Phone.API.Models.PhoneLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("From");

                    b.Property<string>("Message");

                    b.HasKey("Id");

                    b.ToTable("PhoneLog");
                });

            modelBuilder.Entity("Phone.API.Models.PhoneContact", b =>
                {
                    b.HasOne("Phone.API.Models.PhoneLog", "PhoneLog")
                        .WithMany("PhoneContacts")
                        .HasForeignKey("PhoneLogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
