// <auto-generated />
using Email.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Email.API.Migrations
{
    [DbContext(typeof(EmailContext))]
    [Migration("20180124182758_AddApplicationTable")]
    partial class AddApplicationTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Email.API.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("Email.API.Models.EmailContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContactType");

                    b.Property<string>("DisplayName");

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<Guid>("EmailLogId");

                    b.HasKey("Id");

                    b.HasIndex("EmailLogId");

                    b.ToTable("EmailContact");
                });

            modelBuilder.Entity("Email.API.Models.EmailLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<DateTime>("DateTimeSent");

                    b.Property<bool>("IsBodyHtml");

                    b.Property<string>("Priority");

                    b.Property<string>("Subject");

                    b.HasKey("Id");

                    b.ToTable("EmailLog");
                });

            modelBuilder.Entity("Email.API.Models.EmailContact", b =>
                {
                    b.HasOne("Email.API.Models.EmailLog", "EmailLog")
                        .WithMany("EmailContacts")
                        .HasForeignKey("EmailLogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
