//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocPortalStreamService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/PCN.DocPortal")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DocPortalStreamService.DownloadDocumentResultHeader))]
    public partial class Result : object
    {
        
        private string ErrorsField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadDocumentResultHeader", Namespace="http://schemas.datacontract.org/2004/07/PCN.DocPortal")]
    public partial class DownloadDocumentResultHeader : DocPortalStreamService.Result
    {
        
        private string ContentTypeField;
        
        private string DocNameField;
        
        private long LengthField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType
        {
            get
            {
                return this.ContentTypeField;
            }
            set
            {
                this.ContentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocName
        {
            get
            {
                return this.DocNameField;
            }
            set
            {
                this.DocNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                this.LengthField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserClientOrder", Namespace="http://schemas.datacontract.org/2004/07/PCN.DocPortal")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DocPortalStreamService.UploadDocumentRequestHeader))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DocPortalStreamService.DownloadDocumentRequest))]
    public partial class UserClientOrder : object
    {
        
        private DocPortalStreamService.ClientOrder ClientOrderField;
        
        private DocPortalStreamService.User UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DocPortalStreamService.ClientOrder ClientOrder
        {
            get
            {
                return this.ClientOrderField;
            }
            set
            {
                this.ClientOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DocPortalStreamService.User User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientOrder", Namespace="http://schemas.datacontract.org/2004/07/PCN.DocPortal")]
    public partial class ClientOrder : object
    {
        
        private string ClientNumberField;
        
        private string OrderNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientNumber
        {
            get
            {
                return this.ClientNumberField;
            }
            set
            {
                this.ClientNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderNumber
        {
            get
            {
                return this.OrderNumberField;
            }
            set
            {
                this.OrderNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PCN.DocPortal")]
    public partial class User : object
    {
        
        private DocPortalStreamService.AppType AppField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DocPortalStreamService.AppType App
        {
            get
            {
                return this.AppField;
            }
            set
            {
                this.AppField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadDocumentRequestHeader", Namespace="http://schemas.datacontract.org/2004/07/PCN.DocPortal")]
    public partial class UploadDocumentRequestHeader : DocPortalStreamService.UserClientOrder
    {
        
        private string ContentTypeField;
        
        private DocPortalStreamService.DocGroupType DocGroupField;
        
        private string DocNameField;
        
        private string DocTypeField;
        
        private string[] DocTypesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentType
        {
            get
            {
                return this.ContentTypeField;
            }
            set
            {
                this.ContentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DocPortalStreamService.DocGroupType DocGroup
        {
            get
            {
                return this.DocGroupField;
            }
            set
            {
                this.DocGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocName
        {
            get
            {
                return this.DocNameField;
            }
            set
            {
                this.DocNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocType
        {
            get
            {
                return this.DocTypeField;
            }
            set
            {
                this.DocTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DocTypes
        {
            get
            {
                return this.DocTypesField;
            }
            set
            {
                this.DocTypesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadDocumentRequest", Namespace="http://schemas.datacontract.org/2004/07/PCN.DocPortal")]
    public partial class DownloadDocumentRequest : DocPortalStreamService.UserClientOrder
    {
        
        private System.Nullable<DocPortalStreamService.DocGroupType> DocGroupField;
        
        private string DocNameField;
        
        private System.Nullable<System.Guid> DocRepoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<DocPortalStreamService.DocGroupType> DocGroup
        {
            get
            {
                return this.DocGroupField;
            }
            set
            {
                this.DocGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocName
        {
            get
            {
                return this.DocNameField;
            }
            set
            {
                this.DocNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> DocRepoId
        {
            get
            {
                return this.DocRepoIdField;
            }
            set
            {
                this.DocRepoIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocGroupType", Namespace="http://schemas.datacontract.org/2004/07/PCN.DocPortal")]
    public enum DocGroupType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Client = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vendor = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internal = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deliverable = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppType", Namespace="http://schemas.datacontract.org/2004/07/PCN.DocPortal")]
    public enum AppType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eClosings = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Client Portal")]
        ClientPortal = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute(Value="Vendor Portal")]
        VendorPortal = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        eReader = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailApi = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocPortalStreamService.IDocPortalStreamService")]
    public interface IDocPortalStreamService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocPortalStreamService/DownloadDocument", ReplyAction="http://tempuri.org/IDocPortalStreamService/DownloadDocumentResponse")]
        System.Threading.Tasks.Task<DocPortalStreamService.DownloadDocumentResultContract> DownloadDocumentAsync(DocPortalStreamService.DownloadDocumentRequestContract request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocPortalStreamService/UploadDocument", ReplyAction="http://tempuri.org/IDocPortalStreamService/UploadDocumentResponse")]
        System.Threading.Tasks.Task<DocPortalStreamService.UploadDocumentResponse> UploadDocumentAsync(DocPortalStreamService.UploadDocumentRequestContract request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadDocumentRequestContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadDocumentRequestContract
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public DocPortalStreamService.DownloadDocumentRequest DownloadDocumentRequest;
        
        public DownloadDocumentRequestContract()
        {
        }
        
        public DownloadDocumentRequestContract(DocPortalStreamService.DownloadDocumentRequest DownloadDocumentRequest)
        {
            this.DownloadDocumentRequest = DownloadDocumentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadDocumentResultContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadDocumentResultContract
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public DocPortalStreamService.DownloadDocumentResultHeader DownloadDocumentResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] FileByteStream;
        
        public DownloadDocumentResultContract()
        {
        }
        
        public DownloadDocumentResultContract(DocPortalStreamService.DownloadDocumentResultHeader DownloadDocumentResultHeader, byte[] FileByteStream)
        {
            this.DownloadDocumentResultHeader = DownloadDocumentResultHeader;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadDocumentRequestContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadDocumentRequestContract
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public DocPortalStreamService.UploadDocumentRequestHeader UploadDocumentRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public byte[] FileByteStream;
        
        public UploadDocumentRequestContract()
        {
        }
        
        public UploadDocumentRequestContract(DocPortalStreamService.UploadDocumentRequestHeader UploadDocumentRequestHeader, byte[] FileByteStream)
        {
            this.UploadDocumentRequestHeader = UploadDocumentRequestHeader;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDocumentResponse
    {
        
        public UploadDocumentResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface IDocPortalStreamServiceChannel : DocPortalStreamService.IDocPortalStreamService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class DocPortalStreamServiceClient : System.ServiceModel.ClientBase<DocPortalStreamService.IDocPortalStreamService>, DocPortalStreamService.IDocPortalStreamService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DocPortalStreamServiceClient() : 
                base(DocPortalStreamServiceClient.GetDefaultBinding(), DocPortalStreamServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IDocPortalStreamService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocPortalStreamServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(DocPortalStreamServiceClient.GetBindingForEndpoint(endpointConfiguration), DocPortalStreamServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocPortalStreamServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DocPortalStreamServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocPortalStreamServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DocPortalStreamServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocPortalStreamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocPortalStreamService.DownloadDocumentResultContract> DocPortalStreamService.IDocPortalStreamService.DownloadDocumentAsync(DocPortalStreamService.DownloadDocumentRequestContract request)
        {
            return base.Channel.DownloadDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocPortalStreamService.DownloadDocumentResultContract> DownloadDocumentAsync(DocPortalStreamService.DownloadDocumentRequest DownloadDocumentRequest)
        {
            DocPortalStreamService.DownloadDocumentRequestContract inValue = new DocPortalStreamService.DownloadDocumentRequestContract();
            inValue.DownloadDocumentRequest = DownloadDocumentRequest;
            return ((DocPortalStreamService.IDocPortalStreamService)(this)).DownloadDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DocPortalStreamService.UploadDocumentResponse> DocPortalStreamService.IDocPortalStreamService.UploadDocumentAsync(DocPortalStreamService.UploadDocumentRequestContract request)
        {
            return base.Channel.UploadDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<DocPortalStreamService.UploadDocumentResponse> UploadDocumentAsync(DocPortalStreamService.UploadDocumentRequestHeader UploadDocumentRequestHeader, byte[] FileByteStream)
        {
            DocPortalStreamService.UploadDocumentRequestContract inValue = new DocPortalStreamService.UploadDocumentRequestContract();
            inValue.UploadDocumentRequestHeader = UploadDocumentRequestHeader;
            inValue.FileByteStream = FileByteStream;
            return ((DocPortalStreamService.IDocPortalStreamService)(this)).UploadDocumentAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDocPortalStreamService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IDocPortalStreamService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:10082/DocPortalStreamService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DocPortalStreamServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IDocPortalStreamService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DocPortalStreamServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IDocPortalStreamService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IDocPortalStreamService,
        }
    }
}
